
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.3.0
 * Query Engine version: 9d6ad21cbbceab97458517b147a6a09ff43aa735
 */
Prisma.prismaVersion = {
  client: "7.3.0",
  engine: "9d6ad21cbbceab97458517b147a6a09ff43aa735"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  emailVerified: 'emailVerified',
  name: 'name',
  avatar: 'avatar',
  password: 'password',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.KidooScalarFieldEnum = {
  id: 'id',
  name: 'name',
  model: 'model',
  macAddress: 'macAddress',
  bluetoothMacAddress: 'bluetoothMacAddress',
  deviceId: 'deviceId',
  firmwareVersion: 'firmwareVersion',
  lastConnected: 'lastConnected',
  isConnected: 'isConnected',
  wifiSSID: 'wifiSSID',
  userId: 'userId',
  isSynced: 'isSynced',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  brightness: 'brightness',
  sleepTimeout: 'sleepTimeout',
  sleepColorR: 'sleepColorR',
  sleepColorG: 'sleepColorG',
  sleepColorB: 'sleepColorB',
  sleepEffect: 'sleepEffect'
};

exports.Prisma.TagScalarFieldEnum = {
  id: 'id',
  tagId: 'tagId',
  uid: 'uid',
  name: 'name',
  type: 'type',
  kidooId: 'kidooId',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires'
};

exports.Prisma.VerificationTokenScalarFieldEnum = {
  identifier: 'identifier',
  token: 'token',
  expires: 'expires'
};

exports.Prisma.FileScalarFieldEnum = {
  id: 'id',
  tagId: 'tagId',
  userId: 'userId',
  url: 'url',
  path: 'path',
  fileName: 'fileName',
  originalName: 'originalName',
  size: 'size',
  mimeType: 'mimeType',
  order: 'order',
  disabled: 'disabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.KidooConfigBasicScalarFieldEnum = {
  id: 'id',
  kidooId: 'kidooId',
  storageTotalBytes: 'storageTotalBytes',
  storageFreeBytes: 'storageFreeBytes',
  storageUsedBytes: 'storageUsedBytes',
  storageFreePercent: 'storageFreePercent',
  storageUsedPercent: 'storageUsedPercent',
  storageLastUpdated: 'storageLastUpdated',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.KidooConfigDreamScalarFieldEnum = {
  id: 'id',
  kidooId: 'kidooId',
  colorR: 'colorR',
  colorG: 'colorG',
  colorB: 'colorB',
  brightness: 'brightness',
  allNight: 'allNight',
  effect: 'effect',
  wakeupColorR: 'wakeupColorR',
  wakeupColorG: 'wakeupColorG',
  wakeupColorB: 'wakeupColorB',
  wakeupBrightness: 'wakeupBrightness',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.KidooConfigDreamBedtimeScheduleScalarFieldEnum = {
  id: 'id',
  kidooConfigDreamId: 'kidooConfigDreamId',
  weekday: 'weekday',
  hour: 'hour',
  minute: 'minute',
  activated: 'activated',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.KidooConfigDreamWakeupScheduleScalarFieldEnum = {
  id: 'id',
  kidooConfigDreamId: 'kidooConfigDreamId',
  weekday: 'weekday',
  hour: 'hour',
  minute: 'minute',
  activated: 'activated',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.TagType = exports.$Enums.TagType = {
  MUSIC: 'MUSIC',
  STORY: 'STORY',
  SOUND: 'SOUND'
};

exports.Prisma.ModelName = {
  User: 'User',
  Kidoo: 'Kidoo',
  Tag: 'Tag',
  Account: 'Account',
  Session: 'Session',
  VerificationToken: 'VerificationToken',
  File: 'File',
  KidooConfigBasic: 'KidooConfigBasic',
  KidooConfigDream: 'KidooConfigDream',
  KidooConfigDreamBedtimeSchedule: 'KidooConfigDreamBedtimeSchedule',
  KidooConfigDreamWakeupSchedule: 'KidooConfigDreamWakeupSchedule'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
