
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.3.0
 * Query Engine version: 9d6ad21cbbceab97458517b147a6a09ff43aa735
 */
Prisma.prismaVersion = {
  client: "7.3.0",
  engine: "9d6ad21cbbceab97458517b147a6a09ff43aa735"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.CharacterScalarFieldEnum = {
  id: 'id',
  name: 'name',
  defaultImageUrl: 'defaultImageUrl',
  sex: 'sex',
  personality: 'personality',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  stylePrompt: 'stylePrompt',
  imageHeight: 'imageHeight',
  imageWidth: 'imageWidth',
  characterContext: 'characterContext'
};

exports.Prisma.EmotionScalarFieldEnum = {
  id: 'id',
  key: 'key',
  label: 'label',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  promptCustom: 'promptCustom'
};

exports.Prisma.ClipScalarFieldEnum = {
  id: 'id',
  characterId: 'characterId',
  emotionId: 'emotionId',
  status: 'status',
  fileUrl: 'fileUrl',
  sha256: 'sha256',
  sizeBytes: 'sizeBytes',
  width: 'width',
  height: 'height',
  fps: 'fps',
  frames: 'frames',
  durationS: 'durationS',
  prompt: 'prompt',
  modelName: 'modelName',
  previewUrl: 'previewUrl',
  weight: 'weight',
  tags: 'tags',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  xaiJobId: 'xaiJobId',
  loopStartFrame: 'loopStartFrame',
  loopEndFrame: 'loopEndFrame',
  workingPreviewUrl: 'workingPreviewUrl',
  variantPrompt: 'variantPrompt',
  trigger: 'trigger',
  variant: 'variant'
};

exports.Prisma.ClipArtifactScalarFieldEnum = {
  id: 'id',
  clipId: 'clipId',
  frameIndex: 'frameIndex',
  name: 'name',
  x: 'x',
  y: 'y',
  w: 'w',
  h: 'h',
  cornerStyle: 'cornerStyle',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  imageUrl: 'imageUrl'
};

exports.Prisma.ClipFaceRegionScalarFieldEnum = {
  id: 'id',
  clipId: 'clipId',
  regionKey: 'regionKey',
  x: 'x',
  y: 'y',
  w: 'w',
  h: 'h',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  frameIndex: 'frameIndex',
  cornerStyle: 'cornerStyle',
  imageUrl: 'imageUrl'
};

exports.Prisma.EmotionVideoScalarFieldEnum = {
  id: 'id',
  emotionId: 'emotionId',
  sourceClipId: 'sourceClipId',
  name: 'name',
  fps: 'fps',
  width: 'width',
  height: 'height',
  status: 'status',
  binUrl: 'binUrl',
  sha256: 'sha256',
  sizeBytes: 'sizeBytes',
  durationS: 'durationS',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  exitTimeline: 'exitTimeline',
  introTimeline: 'introTimeline',
  loopTimeline: 'loopTimeline',
  totalFrames: 'totalFrames',
  idxUrl: 'idxUrl',
  animUrl: 'animUrl'
};

exports.Prisma.EmotionDeviceScalarFieldEnum = {
  id: 'id',
  characterId: 'characterId',
  pubnubChannel: 'pubnubChannel',
  mode: 'mode',
  isCharging: 'isCharging',
  lastSeenAt: 'lastSeenAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DeviceClipCacheScalarFieldEnum = {
  deviceId: 'deviceId',
  emotionId: 'emotionId',
  slot: 'slot',
  clipId: 'clipId',
  lastSeenAt: 'lastSeenAt',
  lastPlayedAt: 'lastPlayedAt'
};

exports.Prisma.RuleScalarFieldEnum = {
  id: 'id',
  characterId: 'characterId',
  enabled: 'enabled',
  priority: 'priority',
  cooldownMs: 'cooldownMs',
  eventType: 'eventType',
  eventKey: 'eventKey',
  conditions: 'conditions',
  response: 'response',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ObjectTypeScalarFieldEnum = {
  id: 'id',
  key: 'key',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RfidObjectScalarFieldEnum = {
  uid: 'uid',
  objectTypeId: 'objectTypeId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  emailVerified: 'emailVerified',
  name: 'name',
  avatar: 'avatar',
  password: 'password',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  isAdmin: 'isAdmin'
};

exports.Prisma.KidooScalarFieldEnum = {
  id: 'id',
  name: 'name',
  model: 'model',
  macAddress: 'macAddress',
  deviceId: 'deviceId',
  firmwareVersion: 'firmwareVersion',
  lastConnected: 'lastConnected',
  isConnected: 'isConnected',
  wifiSSID: 'wifiSSID',
  userId: 'userId',
  isSynced: 'isSynced',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  bluetoothMacAddress: 'bluetoothMacAddress',
  brightness: 'brightness',
  sleepColorB: 'sleepColorB',
  sleepColorG: 'sleepColorG',
  sleepColorR: 'sleepColorR',
  sleepEffect: 'sleepEffect',
  sleepTimeout: 'sleepTimeout'
};

exports.Prisma.TagScalarFieldEnum = {
  id: 'id',
  uid: 'uid',
  name: 'name',
  kidooId: 'kidooId',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  tagId: 'tagId',
  type: 'type'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires'
};

exports.Prisma.VerificationTokenScalarFieldEnum = {
  identifier: 'identifier',
  token: 'token',
  expires: 'expires'
};

exports.Prisma.FirmwareScalarFieldEnum = {
  id: 'id',
  model: 'model',
  version: 'version',
  url: 'url',
  path: 'path',
  fileName: 'fileName',
  fileSize: 'fileSize',
  createdAt: 'createdAt',
  changelog: 'changelog',
  partCount: 'partCount'
};

exports.Prisma.FileScalarFieldEnum = {
  id: 'id',
  tagId: 'tagId',
  userId: 'userId',
  url: 'url',
  path: 'path',
  fileName: 'fileName',
  originalName: 'originalName',
  size: 'size',
  mimeType: 'mimeType',
  order: 'order',
  disabled: 'disabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.KidooConfigBasicScalarFieldEnum = {
  id: 'id',
  kidooId: 'kidooId',
  storageTotalBytes: 'storageTotalBytes',
  storageFreeBytes: 'storageFreeBytes',
  storageUsedBytes: 'storageUsedBytes',
  storageFreePercent: 'storageFreePercent',
  storageUsedPercent: 'storageUsedPercent',
  storageLastUpdated: 'storageLastUpdated',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.KidooConfigDreamScalarFieldEnum = {
  id: 'id',
  kidooId: 'kidooId',
  colorR: 'colorR',
  colorG: 'colorG',
  colorB: 'colorB',
  brightness: 'brightness',
  allNight: 'allNight',
  effect: 'effect',
  wakeupColorR: 'wakeupColorR',
  wakeupColorG: 'wakeupColorG',
  wakeupColorB: 'wakeupColorB',
  wakeupBrightness: 'wakeupBrightness',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.KidooConfigDreamBedtimeScheduleScalarFieldEnum = {
  id: 'id',
  kidooConfigDreamId: 'kidooConfigDreamId',
  weekday: 'weekday',
  hour: 'hour',
  minute: 'minute',
  activated: 'activated',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.KidooConfigDreamWakeupScheduleScalarFieldEnum = {
  id: 'id',
  kidooConfigDreamId: 'kidooConfigDreamId',
  weekday: 'weekday',
  hour: 'hour',
  minute: 'minute',
  activated: 'activated',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.CharacterSex = exports.$Enums.CharacterSex = {
  FEMALE: 'FEMALE',
  MALE: 'MALE'
};

exports.CharacterPersonality = exports.$Enums.CharacterPersonality = {
  TIMID: 'TIMID',
  GRUMPY: 'GRUMPY',
  FUNNY: 'FUNNY',
  ALWAYS_HUNGRY: 'ALWAYS_HUNGRY',
  BASIC: 'BASIC'
};

exports.ClipStatus = exports.$Enums.ClipStatus = {
  DRAFT: 'DRAFT',
  GENERATING: 'GENERATING',
  READY: 'READY',
  FAILED: 'FAILED',
  DISABLED: 'DISABLED'
};

exports.CornerStyle = exports.$Enums.CornerStyle = {
  ROUNDED: 'ROUNDED',
  SQUARE: 'SQUARE'
};

exports.FaceRegionKey = exports.$Enums.FaceRegionKey = {
  LEFT_EYE: 'LEFT_EYE',
  RIGHT_EYE: 'RIGHT_EYE',
  MOUTH: 'MOUTH'
};

exports.EmotionDeviceMode = exports.$Enums.EmotionDeviceMode = {
  NORMAL: 'NORMAL',
  CHARGING: 'CHARGING',
  SLEEP: 'SLEEP'
};

exports.EventType = exports.$Enums.EventType = {
  RFID: 'RFID',
  TEMP: 'TEMP',
  IMU: 'IMU',
  TOUCH: 'TOUCH',
  POWER: 'POWER',
  SYSTEM: 'SYSTEM'
};

exports.EventKey = exports.$Enums.EventKey = {
  TAG_PRESENT: 'TAG_PRESENT',
  TAG_ABSENT: 'TAG_ABSENT',
  TEMP_READING: 'TEMP_READING',
  TEMP_HOT: 'TEMP_HOT',
  TEMP_COLD: 'TEMP_COLD',
  IMU_SHAKE: 'IMU_SHAKE',
  IMU_TILT: 'IMU_TILT',
  TOUCH_TAP: 'TOUCH_TAP',
  TOUCH_LONG: 'TOUCH_LONG',
  CHARGING_STARTED: 'CHARGING_STARTED',
  CHARGING_STOPPED: 'CHARGING_STOPPED',
  SLEEP_ENTER: 'SLEEP_ENTER',
  SLEEP_EXIT: 'SLEEP_EXIT',
  CUSTOM: 'CUSTOM'
};

exports.KidooModel = exports.$Enums.KidooModel = {
  basic: 'basic',
  dream: 'dream'
};

exports.TagType = exports.$Enums.TagType = {
  MUSIC: 'MUSIC',
  STORY: 'STORY',
  SOUND: 'SOUND'
};

exports.Prisma.ModelName = {
  Character: 'Character',
  Emotion: 'Emotion',
  Clip: 'Clip',
  ClipArtifact: 'ClipArtifact',
  ClipFaceRegion: 'ClipFaceRegion',
  EmotionVideo: 'EmotionVideo',
  EmotionDevice: 'EmotionDevice',
  DeviceClipCache: 'DeviceClipCache',
  Rule: 'Rule',
  ObjectType: 'ObjectType',
  RfidObject: 'RfidObject',
  User: 'User',
  Kidoo: 'Kidoo',
  Tag: 'Tag',
  Account: 'Account',
  Session: 'Session',
  VerificationToken: 'VerificationToken',
  Firmware: 'Firmware',
  File: 'File',
  KidooConfigBasic: 'KidooConfigBasic',
  KidooConfigDream: 'KidooConfigDream',
  KidooConfigDreamBedtimeSchedule: 'KidooConfigDreamBedtimeSchedule',
  KidooConfigDreamWakeupSchedule: 'KidooConfigDreamWakeupSchedule'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
